In [2]:
import numpy as np

In [3]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.sum(a,axis=0)

array([12, 15, 18])

In [5]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [6]:
[np.trace(a)]

[np.int64(15)]

In [7]:
np.flip(a,axis=1)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [8]:
[np.trace(np.flip(a,axis=1))]

[np.int64(15)]

In [14]:
a[0][0]=0
a[2][2]=0
wheres=np.argwhere(a==0)
wheres


array([[0, 0],
       [2, 2]])

In [18]:
for where in wheres:
    where=tuple(where)
    # 传入tuple作为index
    print(f"where:{where},a[where]:{a[where]}")

where:(np.int64(0), np.int64(0)),a[where]:0
where:(np.int64(2), np.int64(2)),a[where]:0


In [23]:
def hash(state:np.ndarray):
    return tuple(state.reshape(9))

hash(a)
b={}
b[tuple(a.reshape(9))]=1